Add retry to pushes in createNewVersion

diff --git a/.github/workflows/createNewVersion.yml b/.github/workflows/createNewVersion.yml
--- a/.github/workflows/createNewVersion.yml
+++ b/.github/workflows/createNewVersion.yml
@@ -85,6 +85,9 @@ jobs:
       - name: Commit new Mobile-Expensify version
         working-directory: Mobile-Expensify
         run: |
+          # Checkout main branch in Mobile-Expensify submodule.
+          # This is IMPORTANT so that when we make changes, we aren't in a detached head state, and when we later push those changes to main, it works!
+          git checkout main
           git add \
             ./Android/AndroidManifest.xml \
             ./app/config/config.json \
@@ -92,7 +95,21 @@ jobs:
             ./iOS/SmartScanExtension/Info.plist \
             ./iOS/NotificationServiceExtension/Info.plist
           git commit -m "Update version to ${{ steps.bumpVersion.outputs.NEW_VERSION }}"
-          git push origin main
+          git push origin main || {
+            echo "Race condition! Mobile-Expensify main was updated while this workflow was running, so push failed. Fetching remote, rebasing, and retrying push once."
+
+            git fetch origin main --depth=1
+
+            if ! git rebase origin/main; then
+              echo "::error:: Rebase failed while retrying Mobile-Expensify push"
+              exit 1
+            fi
+
+            if ! git push origin main; then
+              echo "::error:: Mobile-Expensify change failed to push after rebase"
+              exit 1
+            fi
+          }
 
       - name: Commit new E/App version
         run: |
@@ -109,7 +126,21 @@ jobs:
         run: |
           git add Mobile-Expensify
           git commit -m "Update Mobile-Expensify submodule version to ${{ steps.bumpVersion.outputs.NEW_VERSION }}"
-          git push origin main
+          git push origin main || {
+            echo "Race condition! E/App main was updated while this workflow was running, so push failed. Fetching remote, rebasing, and retrying push once."
+
+            git fetch origin main --depth=1
+
+            if ! git rebase origin/main; then
+              echo "::error:: Rebase failed while retrying Mobile-Expensify push"
+              exit 1
+            fi
+
+            if ! git push origin main; then
+              echo "::error:: Mobile-Expensify change failed to push after rebase"
+              exit 1
+            fi
+          }
 
       - name: Announce failed workflow in Slack
         if: ${{ failure() }}
