Merge pull request #52001 from Expensify/andrew-android-sourcemap
[No QA]Improve file uploading to not exit on error and fix Android sourcemap path

(cherry picked from commit c99ca246dfaaf6726d0b8b99fd4eeda4d3ea2cbb)

(CP triggered by AndrewGable)

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -282,7 +282,7 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: android-hybrid-sourcemap-artifact
-          path: /Users/runner/work/App/App/Mobile-Expensify/Android/build/generated/sourcemaps/react/release/index.android.bundle.map
+          path: /home/runner/work/App/App/Mobile-Expensify/Android/build/generated/sourcemaps/react/release/index.android.bundle.map
 
       - name: Set current App version in Env
         run: echo "VERSION=$(npm run print-version --silent)" >> "$GITHUB_ENV"
@@ -832,7 +832,11 @@ jobs:
 
           # Loop through each file and upload individually (so if one fails, we still have other platforms uploaded)
           for file_entry in "${files[@]}"; do
-            gh release upload ${{ needs.prep.outputs.APP_VERSION }} --repo ${{ github.repository }} --clobber "$file_entry"
+            gh release upload ${{ needs.prep.outputs.APP_VERSION }} --repo ${{ github.repository }} --clobber "$file_entry" || {
+              echo "Failed to upload $file_entry. Continuing with the next file."
+              continue
+            }
+            echo "Successfully uploaded $file_entry."
           done
         env:
           GITHUB_TOKEN: ${{ github.token }}
@@ -891,7 +895,11 @@ jobs:
 
           # Loop through each file and upload individually (so if one fails, we still have other platforms uploaded)
           for file_entry in "${files[@]}"; do
-            gh release upload ${{ needs.prep.outputs.APP_VERSION }} --repo ${{ github.repository }} --clobber "$file_entry"
+            gh release upload ${{ needs.prep.outputs.APP_VERSION }} --repo ${{ github.repository }} --clobber "$file_entry" || {
+              echo "Failed to upload $file_entry. Continuing with the next file."
+              continue
+            }
+            echo "Successfully uploaded $file_entry."
           done
         env:
           GITHUB_TOKEN: ${{ github.token }}
