Add a retry for creating the release as well as verify it

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -627,13 +627,23 @@ jobs:
             echo "Release ${{ needs.prep.outputs.TAG }} already exists, skipping creating it again."
           else
             echo "Release ${{ needs.prep.outputs.TAG }} does not exist, creating it now."
-            gh release create "${{ needs.prep.outputs.TAG }}" ${{ github.ref == 'refs/heads/staging' && '--prerelease' || '' }} \
+            CREATE_RETRIES=0
+            readonly CREATE_MAX_RETRIES=5
+            until gh release create "${{ needs.prep.outputs.TAG }}" ${{ github.ref == 'refs/heads/staging' && '--prerelease' || '' }} \
               --repo "${{ github.repository }}" \
               --title "${{ needs.prep.outputs.TAG }}" \
               ${{ github.ref == 'refs/heads/production' && format('--notes-start-tag {0}', steps.get_last_prod_version.outputs.LAST_PROD_VERSION) || '' }} \
               --generate-notes \
               --verify-tag \
-              --target "${{ github.ref }}"
+              --target "${{ github.ref }}" || [[ $CREATE_RETRIES -ge $CREATE_MAX_RETRIES ]]; do
+              echo "Failed to create release. Retrying in 3 seconds... ($((CREATE_MAX_RETRIES - ++CREATE_RETRIES)) attempts left)"
+              sleep 3
+            done
+
+            if [[ $CREATE_RETRIES -ge $CREATE_MAX_RETRIES ]]; then
+              echo "Failed to create release after $CREATE_MAX_RETRIES attempts"
+              exit 1
+            fi
 
             RETRIES=0
             readonly MAX_RETRIES=10
