Don't make hiding previous comments critical

diff --git a/.github/workflows/generateTranslations.yml b/.github/workflows/generateTranslations.yml
--- a/.github/workflows/generateTranslations.yml
+++ b/.github/workflows/generateTranslations.yml
@@ -87,7 +87,7 @@ jobs:
                         isMinimized
                       }
                     }
-                  }' -f commentId="$comment_id"
+                  }' -f commentId="$comment_id" || echo "Failed to minimize comment $comment_id"
               done
             fi
 
