Enforce there's no prettier diff in PR checks

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -22,3 +22,9 @@ jobs:
 
       - name: Lint shell scripts with ShellCheck
         run: npm run shellcheck
+
+      - name: Verify there's no Prettier diff
+        run: |
+          source Expensify/App/scripts/shellUtils.sh
+          npm run prettier
+          git diff --name-only --exit-code || error 'Error: Prettier diff detected! Please run \`npm run prettier\` and commit the changes.'
