Fixed action yml lint/syntax issues

diff --git a/.github/workflows/preDeploy.yml b/.github/workflows/preDeploy.yml
--- a/.github/workflows/preDeploy.yml
+++ b/.github/workflows/preDeploy.yml
@@ -10,6 +10,7 @@ jobs:
 
   test:
     # uses: Expensify/App/.github/workflows/test.yml@main
+    runs-on: ubuntu-latest
     name: jest (job ${{ matrix.chunk }})
     strategy:
       fail-fast: false
@@ -18,39 +19,36 @@ jobs:
     env:
       CI: true
     steps:
-      if: ${{ github.actor != 'OSBotify' || github.event_name == 'workflow_call' }}
-      runs-on: ubuntu-latest
-      steps:
-        - uses: Expensify/App/.github/actions/composite/setupNode@main
+      # if: ${{ github.actor != 'OSBotify' || github.event_name == 'workflow_call' }}
+      - uses: Expensify/App/.github/actions/composite/setupNode@main
+      # If automatic signing is enabled, iOS builds will fail, so ensure we always have the proper profile specified
+      - name: Check Provisioning Style
+        run: |
+          if grep -q 'PROVISIONING_PROFILE_SPECIFIER = chat_expensify_appstore' ios/NewExpensify.xcodeproj/project.pbxproj; then
+            exit 0
+          else
+            echo "Error: Automatic provisioning style is not allowed!"
+            exit 1
+          fi
 
-        # If automatic signing is enabled, iOS builds will fail, so ensure we always have the proper profile specified
-        - name: Check Provisioning Style
-          run: |
-            if grep -q 'PROVISIONING_PROFILE_SPECIFIER = chat_expensify_appstore' ios/NewExpensify.xcodeproj/project.pbxproj; then
-              exit 0
-            else
-              echo "Error: Automatic provisioning style is not allowed!"
-              exit 1
-            fi
+      - name: Cache Jest cache
+        id: cache-jest-cache
+        uses: actions/cache@v1
+        with:
+          path: .jest-cache
+          key: ${{ runner.os }}-jest
 
-        - name: Cache Jest cache
-          id: cache-jest-cache
-          uses: actions/cache@v1
-          with:
-            path: .jest-cache
-            key: ${{ runner.os }}-${{ matrix.node-version }}-jest
+      - name: All Unit Tests
+        if: ${{ fromJSON(matrix.chunk) < 2 }}
+        run: npx jest --listTests --json --testPathIgnorePatterns=loginTest.js | jq -cM '[_nwise(length / 3 | ceil)]' | jq '.[${{ matrix.chunk }}] | .[] | @text' | xargs yarn test
+      
+      - name: Login Unit Tests
+        if: ${{ fromJSON(matrix.chunk) == 2 }}
+        run: npx jest --listTests --json loginTest.js | jq '.[] | @text' | xargs yarn test
 
-        -name: All Unit Tests
-          if: ${{ fromJSON(matrix.chunk) < 2 }}
-          run: npx jest --listTests --json --testPathIgnorePatterns=loginTest.js | jq -cM '[_nwise(length / 3 | ceil)]' | jq '.[${{ matrix.chunk }}] | .[] | @text' | xargs yarn test
-        
-        - name: Login Unit Tests
-          if: ${{ fromJSON(matrix.chunk) === 2 }}
-          run: npx jest --listTests --json loginTest.js | jq '.[] | @text' | xargs yarn test
-
-        - name: Pull Request Tests
-          if: ${{ fromJSON(matrix.chunk) === 3 }}
-          run: tests/unit/getPullRequestsMergedBetweenTest.sh
+      - name: Pull Request Tests
+        if: ${{ fromJSON(matrix.chunk) == 3 }}
+        run: tests/unit/getPullRequestsMergedBetweenTest.sh
 
   confirmPassingBuild:
     runs-on: ubuntu-latest
