Make preDeploy continue if lint and test succeed

diff --git a/.github/workflows/preDeploy.yml b/.github/workflows/preDeploy.yml
--- a/.github/workflows/preDeploy.yml
+++ b/.github/workflows/preDeploy.yml
@@ -14,14 +14,17 @@ jobs:
   confirmPassingBuild:
     runs-on: ubuntu-latest
     needs: [lint, test]
-    if: ${{ always() && (needs.lint.result == 'failure' || needs.test.result == 'failure') }}
+    if: ${{ always() }}
 
     steps:
+      - id: didBuildFail
+        run: echo "::set-output name=DID_BUILD_FAIL::${{ needs.lint.result == 'failure' || needs.test.result == 'failure' }}"
+
       # This Slack step is duplicated in all workflows, if you make a change to this step, make sure to update all
       # the other workflows with the same change
       - uses: 8398a7/action-slack@v3
         name: Job failed Slack notification
-        if: ${{ failure() }}
+        if: ${{ fromJSON(steps.didBuildFail.DID_BUILD_FAIL) }}
         with:
           status: custom
           fields: workflow, repo
@@ -37,6 +40,9 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ github.token }}
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
+
+      - if: ${{ fromJSON(steps.didBuildFail.DID_BUILD_FAIL) }}
+        run: exit 1
 
   chooseDeployActions:
     runs-on: ubuntu-latest
