restore: restore to previous state

diff --git a/.github/workflows/prettier.yml b/.github/workflows/prettier.yml
--- a/.github/workflows/prettier.yml
+++ b/.github/workflows/prettier.yml
@@ -26,5 +26,11 @@ jobs:
         with:
           IS_DESKTOP_BUILD: true
 
-      - name: Run Prettier check
-        run: npm run prettier --check .
+      - name: Verify there's no Prettier diff
+        run: |
+          npm run prettier -- --log-level error
+          if ! git diff --name-only --exit-code; then
+            # shellcheck disable=SC2016
+            echo 'Error: Prettier diff detected! Please run `npm run prettier` and commit the changes.'
+            exit 1
+          fi
