fix: don't fail react compiler compliance workflow

diff --git a/.github/workflows/react-compiler-compliance.yml b/.github/workflows/react-compiler-compliance.yml
--- a/.github/workflows/react-compiler-compliance.yml
+++ b/.github/workflows/react-compiler-compliance.yml
@@ -25,7 +25,9 @@ jobs:
         uses: ./.github/actions/composite/setupNode
 
       - name: Run React Compiler Compliance Check
-        run: npm run react-compiler-compliance-check check-changed
+        # In phase 1 of the React Compiler compliance check rollout,
+        # we want to report failures but don't fail the check.
+        run: npm run react-compiler-compliance-check check-changed || true
         env:
           CI: true
           GITHUB_TOKEN: ${{ github.token }}
