Update typecheck

diff --git a/.github/workflows/typecheck.yml b/.github/workflows/typecheck.yml
--- a/.github/workflows/typecheck.yml
+++ b/.github/workflows/typecheck.yml
@@ -20,3 +20,11 @@ jobs:
         run: npm run typecheck
         env:
           CI: true
+
+      - name: Check for new JavaScript files
+        run: |
+          count_new_js=$(git diff --name-only --diff-filter=A main -- '*.{js,jsx}' | grep -cE 'src/libs|src/hooks|src/styles|src/languages')
+          if [ "$count_new_js" -gt "0" ]; then
+            echo "ERROR: Found new JS or JSX files in the /src/libs, /src/hooks, /src/styles, or /src/languages directories."
+            exit 1
+          fi
